development:
  # Sqlite Settings
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_development
  # username: root
  # password:
  # pool: 5
  
test:
  # Sqlite Settings
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_test
  # username: root
  # password:
  # pool: 5
  
staging:
  # Sqlite Settings
  adapter: sqlite3
  database: db/staging.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_staging
  # username: root
  # password:
  # pool: 5
  
production:
  adapter: mysql
  encoding: utf8
  database: swiftkickpress #following rails db naming convention
  username: swiftkick_mysql
  password: sa1ewsa1ew
  host: mysql.swiftkickpress.com
  port: 3306  #not necessary since its the standard mysql port


  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_production
  # username: root
  # password:
  # pool: 5