development: &non_production_settings
  site_url: http://swiftkickpress.local
  site_name: Swiftkick Press
  admin_email: johnhutch+skdev@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Bort
  admin_email: johnhutch+skdev@gmail.com
  
production:
  site_url: http://www.swiftkickpress.com
  site_name: Swiftkick Press
  admin_email: johnhutch+skdev@gmail.com
